Class.getSimpleName throws NoClassDefFoundError in glassfish.
Use class.getName instead of Class.getSimpleName.

Some class load after add my class transformer, so don't remove it
until reset-class be called.